CREATE SCHEMA IF NOT EXISTS user_manager;

set search_path TO "$user", public, user_manager;

CREATE TABLE user_manager.user_status (
	id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar(20) NOT NULL UNIQUE,
	description varchar(50) NULL,
	CONSTRAINT user_status_pk PRIMARY KEY (id)
);


CREATE TABLE user_manager."user" (
	id serial NOT NULL UNIQUE,
	"name" varchar(40) NOT NULL,
	user_status smallint NOT NULL,
	created timestamptz(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified timestamptz(0) NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_fk FOREIGN KEY (user_status) REFERENCES user_manager.user_status(id)
);

CREATE TABLE user_manager."role" (
	id serial NOT NULL UNIQUE,
	"sysname" varchar(20) NOT NULL UNIQUE,
	"name" varchar(20) NOT NULL UNIQUE,
	description varchar(50) NULL,
	created timestamptz(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modified timestamptz(0) NULL,
	CONSTRAINT role_pk PRIMARY KEY (id)
);

CREATE TABLE user_manager.user2role (
	id serial NOT NULL UNIQUE,
	user_id int NOT NULL,
	role_id int NOT NULL,
	CONSTRAINT user2role_pk PRIMARY KEY (id),
	CONSTRAINT user2role_fk FOREIGN KEY (user_id) REFERENCES user_manager."user"(id),
	CONSTRAINT user2role_fk_1 FOREIGN KEY (role_id) REFERENCES user_manager."role"(id),
	UNIQUE (user_id, role_id)
);